document.write( '<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@9\"></script>\n' );
document.write( '<script>\n' );
document.write( 'function copy_data(containerid) {\n' );
document.write( '  var range = document.createRange();\n' );
document.write( '  range.selectNode(containerid); //changed here\n' );
document.write( '  window.getSelection().removeAllRanges(); \n' );
document.write( '  window.getSelection().addRange(range); \n' );
document.write( '  document.execCommand(\"copy\");\n' );
document.write( '  window.getSelection().removeAllRanges();\n' );
document.write( '  Swal.fire({\n' );
document.write( '  position: \'top-end\',\n' );
document.write( '  icon: \'success\',\n' );
document.write( '  title: \'Copied Share Url To ClipBoard\',\n' );
document.write( '  showConfirmButton: false,\n' );
document.write( '  timer: 1500\n' );
document.write( '})\n' );
document.write( '}\n' );
document.write( '</script>\n' );
document.write( '<div id=\"select_txt\">https://tinyurl.com/yzkvrrk6</div>\n' );
document.write( '\n' );
document.write( '<style>\n' );
document.write( '#select_txt {\n' );
document.write( '  opacity:0; \n' );
document.write( '  height: 0px;\n' );
document.write( '  width: 0px;\n' );
document.write( '}\n' );
document.write( '</style>\n' );
document.write( '<div class=\"menu\">\n' );
document.write( '  <ul class=\"menu-options\">\n' );
document.write( '    <li> Iron App Player </li>\n' );
document.write( '    <li> By IronTheCoder </li>\n' );
document.write( '    \n' );
document.write( '    <li class=\"menu-option\"> <button type=\"button\" onclick=\"copy_data(select_txt)\">share</button> </li>\n' );
document.write( '    <li>\n' );
document.write( '      <button class= \"menu-option\" onclick=\"location.href=\'https://nazro-minecraft-skin-editor.weebly.com/\'\" type=\"button\">\n' );
document.write( '         Nazro MC Skin Editor</button>\n' );
document.write( '    </li>\n' );
document.write( '    <li>\n' );
document.write( '      <button class= \"menu-option\" onclick=\"location.href=\'https://iron4apps.weebly.com/\'\" type=\"button\">\n' );
document.write( '         Iron Apps</button>\n' );
document.write( '    </li>\n' );
document.write( '  </ul>\n' );
document.write( '</div>\n' );
document.write( '<style>\n' );
document.write( '      body {\n' );
document.write( '  font-family: \"Roboto\", san-serif;\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.center{\n' );
document.write( '  text-align: center;\n' );
document.write( '}\n' );
document.write( '.menu {\n' );
document.write( '  width: 150px;\n' );
document.write( '  z-index: 1;\n' );
document.write( '  box-shadow: 0 4px 5px 3px rgba(0, 0, 0, 0.2);\n' );
document.write( '  position: fixed;\n' );
document.write( '  display: none;\n' );
document.write( '  transition: 0.2s display ease-in;\n' );
document.write( '\n' );
document.write( '  .menu-options {\n' );
document.write( '    list-style: none;\n' );
document.write( '    padding: 10px 0;\n' );
document.write( '    z-index: 1;\n' );
document.write( '    \n' );
document.write( '    .menu-option {\n' );
document.write( '      font-weight: 500;\n' );
document.write( '      z-index: 1;\n' );
document.write( '      font-size: 14px;\n' );
document.write( '      padding: 10px 40px 10px 20px;\n' );
document.write( '      // border-bottom: 1.5px solid rgba(0, 0, 0, 0.2);\n' );
document.write( '      cursor: pointer;\n' );
document.write( '\n' );
document.write( '      &:hover {\n' );
document.write( '        background: rgba(0, 0, 0, 0.2);\n' );
document.write( '      }\n' );
document.write( '    }\n' );
document.write( '  }\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( 'button{\n' );
document.write( '  background: white;\n' );
document.write( '  border: none;\n' );
document.write( '  \n' );
document.write( '  .next{\n' );
document.write( '    color:green;\n' );
document.write( '  }\n' );
document.write( '  \n' );
document.write( '  &[disabled=\"false\"]:hover{\n' );
document.write( '    .next{\n' );
document.write( '      color: red;\n' );
document.write( '      animation: move 0.5s;\n' );
document.write( '      animation-iteration-count: 2;\n' );
document.write( '    }\n' );
document.write( '  }\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@keyframes move{\n' );
document.write( '  from{\n' );
document.write( '    transform: translate(0%);\n' );
document.write( '  }\n' );
document.write( '  50%{\n' );
document.write( '    transform: translate(-40%);\n' );
document.write( '  }\n' );
document.write( '  to{\n' );
document.write( '    transform: transform(0%);\n' );
document.write( '  }\n' );
document.write( '}\n' );
document.write( 'li {\n' );
document.write( '    list-style-type: none;\n' );
document.write( '}\n' );
document.write( '  </style>\n' );
document.write( '<script>\n' );
document.write( '  const menu = document.querySelector(\".menu\");\n' );
document.write( 'const menuOption = document.querySelector(\".menu-option\");\n' );
document.write( 'let menuVisible = false;\n' );
document.write( '\n' );
document.write( 'const toggleMenu = command => {\n' );
document.write( '  menu.style.display = command === \"show\" ? \"block\" : \"none\";\n' );
document.write( '  menuVisible = !menuVisible;\n' );
document.write( '};\n' );
document.write( '\n' );
document.write( 'const setPosition = ({ top, left }) => {\n' );
document.write( '  menu.style.left = `${left}px`;\n' );
document.write( '  menu.style.top = `${top}px`;\n' );
document.write( '  toggleMenu(\"show\");\n' );
document.write( '};\n' );
document.write( '\n' );
document.write( 'window.addEventListener(\"click\", e => {\n' );
document.write( '  if (menuVisible) toggleMenu(\"hide\");\n' );
document.write( '});\n' );
document.write( '\n' );
document.write( 'menuOption.addEventListener(\"click\", e => {\n' );
document.write( '  console.log(\"mouse-option\", e.target.innerHTML);\n' );
document.write( '});\n' );
document.write( '\n' );
document.write( 'window.addEventListener(\"contextmenu\", e => {\n' );
document.write( '  e.preventDefault();\n' );
document.write( '  const origin = {\n' );
document.write( '    left: e.pageX,\n' );
document.write( '    top: e.pageY\n' );
document.write( '  };\n' );
document.write( '  setPosition(origin);\n' );
document.write( '  return false;\n' );
document.write( '});\n' );
document.write( '</script>' );
